server:
  port: 8080

spring:
  application:
    name: demo
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/swblog?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root

#  待修改
mybatis:
  mapper-locations: classpath:Mapper/*.xml
  # type-aliases-package: com.atguigu.springboot.dao

# swagger文档
swagger:
  enable: true
  application-name: ${spring.application.name}
  application-version: 1.0
  application-description: springfox swagger

# 分页插件
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true